"""probador por fotos y retirada del catalogo de la camara

El probador deja de ser una cámara en vivo con su propio catálogo de prendas y
pasa a vestir la FOTO de una persona con una prenda del taller:

- `person_photos`: la foto de la persona. Borrarla borra sus pruebas.
- `try_ons`: la prueba. La prenda sale de una prueba de tela o de una prenda
  subida, las dos con SET NULL: el resultado es del usuario aunque borre el
  origen, y guarda la prenda exacta que se usó.
- `garments` se elimina: era el catálogo de la cámara, sembrado con datos de
  ejemplo. El downgrade recrea la tabla vacía; sus imágenes de ejemplo siguen
  en `assets/prendas-de-ejemplo/`.

Revision ID: 32d71eca2214
Revises: 84f6b95eefae
Create Date: 2026-09-27 05:39:33.098474+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32d71eca2214'
down_revision: Union[str, Sequence[str], None] = '84f6b95eefae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_photos_user_id'), 'person_photos', ['user_id'], unique=False)
    op.create_table('try_ons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('person_photo_id', sa.Integer(), nullable=False),
    sa.Column('fabric_trial_id', sa.Integer(), nullable=True),
    sa.Column('garment_upload_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('top', 'bottom', 'full', name='garmentcategory', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='trialstatus', native_enum=False, length=32), nullable=False),
    sa.Column('garment_image_key', sa.String(length=512), nullable=True),
    sa.Column('output_image_key', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notice', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('edited_fraction', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fabric_trial_id'], ['fabric_trials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['garment_upload_id'], ['garment_uploads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_photo_id'], ['person_photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_try_ons_fabric_trial_id'), 'try_ons', ['fabric_trial_id'], unique=False)
    op.create_index(op.f('ix_try_ons_garment_upload_id'), 'try_ons', ['garment_upload_id'], unique=False)
    op.create_index(op.f('ix_try_ons_person_photo_id'), 'try_ons', ['person_photo_id'], unique=False)
    op.create_index(op.f('ix_try_ons_status'), 'try_ons', ['status'], unique=False)
    op.create_index(op.f('ix_try_ons_user_id'), 'try_ons', ['user_id'], unique=False)
    op.drop_index(op.f('ix_garments_active'), table_name='garments')
    op.drop_index(op.f('ix_garments_category'), table_name='garments')
    op.drop_table('garments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=160), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('image_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('fabric', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('garments_pkey'))
    )
    op.create_index(op.f('ix_garments_category'), 'garments', ['category'], unique=False)
    op.create_index(op.f('ix_garments_active'), 'garments', ['active'], unique=False)
    op.drop_index(op.f('ix_try_ons_user_id'), table_name='try_ons')
    op.drop_index(op.f('ix_try_ons_status'), table_name='try_ons')
    op.drop_index(op.f('ix_try_ons_person_photo_id'), table_name='try_ons')
    op.drop_index(op.f('ix_try_ons_garment_upload_id'), table_name='try_ons')
    op.drop_index(op.f('ix_try_ons_fabric_trial_id'), table_name='try_ons')
    op.drop_table('try_ons')
    op.drop_index(op.f('ix_person_photos_user_id'), table_name='person_photos')
    op.drop_table('person_photos')
    # ### end Alembic commands ###
