"""disenos, perfil corporal y try-on desde diseno

DOS CORRECCIONES A MANO SOBRE LO QUE GENERO AUTOGENERATE
--------------------------------------------------------
1. Alembic NO detecta CheckConstraints anadidas a una tabla que ya existe.
   La regla "una prueba parte de una prenda O de un diseno, nunca de las dos
   ni de ninguna" habria quedado solo en Python. Se anade abajo a mano.

2. La clave foranea de `design_id` se genero como `create_foreign_key(None, ...)`
   y su `drop_constraint(None, ...)` en el downgrade. Crear sin nombre funciona
   (PostgreSQL lo inventa), pero BORRAR sin nombre revienta: no se puede
   eliminar una constraint llamada None. Se le pone nombre explicito.

Orden importante en el upgrade: primero se permite el nulo en `garment_id`,
DESPUES se anade la CHECK. Al reves, la constraint fallaria contra las filas
existentes mientras la columna sigue siendo NOT NULL.

Revision ID: 65f5946bbfd7
Revises: d49edc91e56b
Create Date: 2026-09-07 04:32:24.339884+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f5946bbfd7'
down_revision: Union[str, Sequence[str], None] = 'd49edc91e56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('inseam_cm', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'analysis', name='measurementsource', native_enum=False, length=32), nullable=False),
    sa.Column('photo_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height_cm IS NULL OR (height_cm BETWEEN 50 AND 260)', name='ck_body_profiles_height_range'),
    sa.CheckConstraint('weight_kg IS NULL OR (weight_kg BETWEEN 20 AND 400)', name='ck_body_profiles_weight_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_profiles_user_id'), 'body_profiles', ['user_id'], unique=True)
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('refinement', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('image_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='designstatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['designs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designs_parent_id'), 'designs', ['parent_id'], unique=False)
    op.create_index(op.f('ix_designs_status'), 'designs', ['status'], unique=False)
    op.create_index(op.f('ix_designs_user_id'), 'designs', ['user_id'], unique=False)
    op.add_column('try_on_sessions', sa.Column('design_id', sa.Integer(), nullable=True))
    op.alter_column('try_on_sessions', 'garment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_try_on_sessions_design_id'), 'try_on_sessions', ['design_id'], unique=False)
    op.create_foreign_key(
        'fk_try_on_sessions_design_id_designs',
        'try_on_sessions', 'designs', ['design_id'], ['id'], ondelete='RESTRICT',
    )

    # Anadida a mano: autogenerate no ve las CHECK sobre tablas existentes.
    # Las filas que ya hay tienen garment_id y design_id nulo, asi que la
    # cumplen; si alguna no lo hiciera, esta orden fallaria y la migracion
    # entera se desharia (PostgreSQL tiene DDL transaccional).
    op.create_check_constraint(
        'ck_try_on_sessions_garment_xor_design',
        'try_on_sessions',
        '(garment_id IS NOT NULL AND design_id IS NULL) '
        'OR (garment_id IS NULL AND design_id IS NOT NULL)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_try_on_sessions_garment_xor_design', 'try_on_sessions', type_='check')
    op.drop_constraint('fk_try_on_sessions_design_id_designs', 'try_on_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_try_on_sessions_design_id'), table_name='try_on_sessions')
    op.alter_column('try_on_sessions', 'garment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('try_on_sessions', 'design_id')
    op.drop_index(op.f('ix_designs_user_id'), table_name='designs')
    op.drop_index(op.f('ix_designs_status'), table_name='designs')
    op.drop_index(op.f('ix_designs_parent_id'), table_name='designs')
    op.drop_table('designs')
    op.drop_index(op.f('ix_body_profiles_user_id'), table_name='body_profiles')
    op.drop_table('body_profiles')
    # ### end Alembic commands ###
