"""esquema inicial etapa 1

Migración fundacional: reproduce el esquema que la Etapa 1 creaba con
`Base.metadata.create_all()`. A partir de aquí, `create_all` deja de correr al
arrancar la aplicación y el esquema lo gobierna Alembic.

Se generó con `--autogenerate` contra una base VACÍA y desechable, no contra
`vfit`. Autogenerate compara los modelos con la base a la que apunta: contra
`vfit`, que ya tenía las tablas creadas, habría producido una migración vacía.

Sobre una base que YA tiene estas tablas (la `vfit` de desarrollo), esta
migración no debe ejecutarse — fallaría con "la relación ya existe". Se marca
como aplicada sin tocar los datos:

    alembic stamp head

Sobre una base vacía se aplica con normalidad:

    alembic upgrade head

Nota sobre los enums: `category` y `status` se materializan como VARCHAR(32)
SIN constraint CHECK. Es el comportamiento de `Enum(native_enum=False)` desde
SQLAlchemy 1.4, donde `create_constraint` vale False por defecto. Los valores
los valida Pydantic en la entrada de la API. Es intencionado: una CHECK
obligaría a una migración cada vez que se añada una categoría, que es
exactamente el coste que se quería evitar al descartar el ENUM nativo.

Revision ID: d49edc91e56b
Revises:
Create Date: 2026-09-06 20:59:15.107774+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49edc91e56b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('dress', 'top', 'bottom', 'outerwear', 'other', name='garmentcategory', native_enum=False, length=32), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garments_active'), 'garments', ['active'], unique=False)
    op.create_index(op.f('ix_garments_category'), 'garments', ['category'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('try_on_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garment_id', sa.Integer(), nullable=False),
    sa.Column('input_image_key', sa.String(length=512), nullable=False),
    sa.Column('output_image_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='tryonstatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_try_on_sessions_garment_id'), 'try_on_sessions', ['garment_id'], unique=False)
    op.create_index(op.f('ix_try_on_sessions_status'), 'try_on_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_try_on_sessions_user_id'), 'try_on_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_try_on_sessions_user_id'), table_name='try_on_sessions')
    op.drop_index(op.f('ix_try_on_sessions_status'), table_name='try_on_sessions')
    op.drop_index(op.f('ix_try_on_sessions_garment_id'), table_name='try_on_sessions')
    op.drop_table('try_on_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_garments_category'), table_name='garments')
    op.drop_index(op.f('ix_garments_active'), table_name='garments')
    op.drop_table('garments')
    # ### end Alembic commands ###
