"""Catálogo de telas, prendas subidas y pruebas.

QUÉ AÑADE
---------
Las tres tablas del producto que describe el Product Vision Board:

- `fabrics`: el catálogo de la tienda textil. Es el centro del producto, y por
  eso lleva ficha técnica completa —composición, ancho del rollo, gramaje,
  precio por metro— y no solo un nombre y una foto: nadie compra tela sin saber
  si con ese ancho le salen las piezas del patrón.
- `garment_uploads`: la prenda o el boceto que trae el usuario. Guarda también
  el RECORTE ya calculado, porque se necesita idéntico para cada tela que se
  pruebe y recalcularlo convertiría diez pruebas en diez recortes.
- `fabric_trials`: la prueba. Es la unidad de negocio —el Vision Board mide
  «pruebas generadas» y «conversión prueba→compra»—, así que guarda con qué
  motor se hizo y cuánto costó en tokens.

NO TOCA NADA DE LO QUE YA HABÍA
-------------------------------
`garments` sigue siendo el catálogo del probador con cámara y se queda como
está. Son dos catálogos para dos productos distintos: uno es el inventario de
una tienda de telas, el otro es ropa para probarse delante del espejo. Mezclarlos
en una tabla habría obligado a que la mitad de las columnas estuvieran siempre
vacías.

Revision ID: 84f6b95eefae
Revises: 1a61ba91aea8
Create Date: 2026-09-18 06:19:44.122519+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f6b95eefae'
down_revision: Union[str, Sequence[str], None] = '1a61ba91aea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fabrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('composition', sa.String(length=160), nullable=True),
    sa.Column('weight_gsm', sa.Integer(), nullable=True),
    sa.Column('width_cm', sa.Integer(), nullable=True),
    sa.Column('price_per_meter', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('color_name', sa.String(length=80), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('pattern', sa.Enum('solid', 'stripes', 'checks', 'print', 'textured', name='fabricpattern', native_enum=False, length=32), nullable=False),
    sa.Column('photo_key', sa.String(length=512), nullable=True),
    sa.Column('texture_key', sa.String(length=512), nullable=True),
    sa.Column('default_repeat', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fabrics_active'), 'fabrics', ['active'], unique=False)
    op.create_index(op.f('ix_fabrics_pattern'), 'fabrics', ['pattern'], unique=False)
    op.create_index(op.f('ix_fabrics_reference'), 'fabrics', ['reference'], unique=False)
    op.create_table('garment_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('photo', 'sketch', name='garmentkind', native_enum=False, length=32), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('mask_key', sa.String(length=512), nullable=True),
    sa.Column('mask_coverage', sa.Float(), nullable=True),
    sa.Column('mask_suspect', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garment_uploads_user_id'), 'garment_uploads', ['user_id'], unique=False)
    op.create_table('fabric_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garment_upload_id', sa.Integer(), nullable=False),
    sa.Column('fabric_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='trialstatus', native_enum=False, length=32), nullable=False),
    sa.Column('method', sa.Enum('retexture', 'ai', name='trialmethod', native_enum=False, length=32), nullable=False),
    sa.Column('repeat_across', sa.Integer(), nullable=False),
    sa.Column('output_image_key', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notice', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('repeat_across > 0', name='ck_fabric_trials_repeat_positivo'),
    sa.ForeignKeyConstraint(['fabric_id'], ['fabrics.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['garment_upload_id'], ['garment_uploads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fabric_trials_fabric_id'), 'fabric_trials', ['fabric_id'], unique=False)
    op.create_index(op.f('ix_fabric_trials_garment_upload_id'), 'fabric_trials', ['garment_upload_id'], unique=False)
    op.create_index(op.f('ix_fabric_trials_status'), 'fabric_trials', ['status'], unique=False)
    op.create_index(op.f('ix_fabric_trials_user_id'), 'fabric_trials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fabric_trials_user_id'), table_name='fabric_trials')
    op.drop_index(op.f('ix_fabric_trials_status'), table_name='fabric_trials')
    op.drop_index(op.f('ix_fabric_trials_garment_upload_id'), table_name='fabric_trials')
    op.drop_index(op.f('ix_fabric_trials_fabric_id'), table_name='fabric_trials')
    op.drop_table('fabric_trials')
    op.drop_index(op.f('ix_garment_uploads_user_id'), table_name='garment_uploads')
    op.drop_table('garment_uploads')
    op.drop_index(op.f('ix_fabrics_reference'), table_name='fabrics')
    op.drop_index(op.f('ix_fabrics_pattern'), table_name='fabrics')
    op.drop_index(op.f('ix_fabrics_active'), table_name='fabrics')
    op.drop_table('fabrics')
    # ### end Alembic commands ###
