"""Solo catálogo y cuentas, y tejido de la prenda.

QUÉ HACE
--------
Retira del esquema las tres tablas que sostenían la parte de IA generativa:
`designs` (diseños por texto), `try_on_sessions` (pruebas generadas por un
modelo) y `body_profiles` (medidas del análisis corporal). Y añade a las
prendas la columna `fabric`.

BORRA DATOS, A PROPÓSITO
------------------------
El historial de pruebas y los diseños guardados desaparecen. No hay forma de
"desactivarlos" conservándolos: la aplicación ya no tiene código que sepa
leerlos, así que mantener las tablas solo dejaría datos huérfanos que nadie
volvería a mirar y que seguirían apareciendo en cada `alembic check`.

El `downgrade` reconstruye las tres tablas VACÍAS. Recupera el esquema, no el
contenido: una migración no puede resucitar filas que ya no existen.

Los archivos de imagen asociados (carpetas `storage/uploads`, `storage/results`,
`storage/designs` y `storage/body`) se borraron a mano en el mismo cambio.
Alembic gobierna el esquema, no el disco.

Revision ID: 1a61ba91aea8
Revises: 65f5946bbfd7
Create Date: 2026-09-14 04:56:59.561191+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a61ba91aea8'
down_revision: Union[str, Sequence[str], None] = '65f5946bbfd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Orden obligatorio: `try_on_sessions` apunta a `designs` con una clave
    # ajena, así que la tabla que referencia cae antes que la referenciada.
    # Al revés, PostgreSQL rechaza el DROP.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_profiles_user_id'), table_name='body_profiles')
    op.drop_table('body_profiles')
    op.drop_index(op.f('ix_try_on_sessions_design_id'), table_name='try_on_sessions')
    op.drop_index(op.f('ix_try_on_sessions_garment_id'), table_name='try_on_sessions')
    op.drop_index(op.f('ix_try_on_sessions_status'), table_name='try_on_sessions')
    op.drop_index(op.f('ix_try_on_sessions_user_id'), table_name='try_on_sessions')
    op.drop_table('try_on_sessions')
    op.drop_index(op.f('ix_designs_parent_id'), table_name='designs')
    op.drop_index(op.f('ix_designs_status'), table_name='designs')
    op.drop_index(op.f('ix_designs_user_id'), table_name='designs')
    op.drop_table('designs')
    # Nullable y sin valor por defecto: las prendas que ya están en el
    # catálogo se quedan sin tejido registrado, que es la verdad. Rellenarlas
    # con "algodón" sería inventarse un dato del que luego depende el encaje.
    op.add_column('garments', sa.Column('fabric', sa.Enum('cotton', 'linen', 'silk', 'wool', 'knit', 'denim', 'leather', 'synthetic', name='garmentfabric', native_enum=False, length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Devuelve las tablas, vacías. Ver la nota de arriba: los datos no vuelven.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garments', 'fabric')
    op.create_table('designs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refinement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['designs.id'], name=op.f('designs_parent_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('designs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('designs_pkey'))
    )
    op.create_index(op.f('ix_designs_user_id'), 'designs', ['user_id'], unique=False)
    op.create_index(op.f('ix_designs_status'), 'designs', ['status'], unique=False)
    op.create_index(op.f('ix_designs_parent_id'), 'designs', ['parent_id'], unique=False)
    op.create_table('try_on_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('garment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_image_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('output_image_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('design_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('garment_id IS NOT NULL AND design_id IS NULL OR garment_id IS NULL AND design_id IS NOT NULL', name=op.f('ck_try_on_sessions_garment_xor_design')),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], name=op.f('fk_try_on_sessions_design_id_designs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], name=op.f('try_on_sessions_garment_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('try_on_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('try_on_sessions_pkey'))
    )
    op.create_index(op.f('ix_try_on_sessions_user_id'), 'try_on_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_try_on_sessions_status'), 'try_on_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_try_on_sessions_garment_id'), 'try_on_sessions', ['garment_id'], unique=False)
    op.create_index(op.f('ix_try_on_sessions_design_id'), 'try_on_sessions', ['design_id'], unique=False)
    op.create_table('body_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('chest_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('waist_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hips_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('inseam_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('photo_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('height_cm IS NULL OR height_cm >= 50::double precision AND height_cm <= 260::double precision', name=op.f('ck_body_profiles_height_range')),
    sa.CheckConstraint('weight_kg IS NULL OR weight_kg >= 20::double precision AND weight_kg <= 400::double precision', name=op.f('ck_body_profiles_weight_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('body_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('body_profiles_pkey'))
    )
    op.create_index(op.f('ix_body_profiles_user_id'), 'body_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###
